/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AMenuItemGroup: typeof import('ant-design-vue/es')['MenuItemGroup']
    AppstoreOutlined: typeof import('@ant-design/icons-vue')['AppstoreOutlined']
    ASubMenu: typeof import('ant-design-vue/es')['SubMenu']
    HelloWorld: typeof import('./common/components/HelloWorld.vue')['default']
    MailOutlined: typeof import('@ant-design/icons-vue')['MailOutlined']
    QqOutlined: typeof import('@ant-design/icons-vue')['QqOutlined']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SettingOutlined: typeof import('@ant-design/icons-vue')['SettingOutlined']
  }
}
